### ISSUE TITLE
Lỗi chữ ký không đúng định dạng

### ISSUE THREAD

**Issue by manhxuanpham** [phanxuanquang/VNPAY.NET#1]
System.UnauthorizedAccessException: 'Chữ ký không hợp lệ'
lỗi xảy ra khi gọi api CallBack
Tôi đã kiểm tra thuật toán Hash trên sandbox : HmacSHA512

**Comment by phanxuanquang** [comment]
Bạn upgrade lên phiên bản `8.3.0` nhé

**Comment by manhxuanpham** [comment]
Đã thử lại và thành công, cảm ơn bạn đã hỗ trợ
